- project:
    check:
      jobs:
        - sf-rpm-build
        - shake-factory-test
        - tox-docs:
            nodeset: python-latest-pod
        - tox-linters:
            nodeset: python-latest-pod
        - tox-py36:
            nodeset: python-latest-pod
    gate:
      jobs:
        - sf-rpm-publish:
            dependencies:
              - sf-rpm-build
              - shake-factory-test
              - tox-docs
              - tox-linters
              - tox-py36
        - sf-rpm-build
        - shake-factory-test
        - tox-docs:
            nodeset: python-latest-pod
        - tox-linters:
            nodeset: python-latest-pod
        - tox-py36:
            nodeset: python-latest-pod
    post:
      jobs:
        - shake-factory-publish-docs
